name: build-test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]
    services:
      mysql:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: cosplay
          TZ: 'Asia/Tokyo'
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        useLockFile: false
    - run: yarn
    - run: yarn build:all
    - run: yarn migrate:test
      env:
        CI: true
    - run: yarn reset:test
    - run: yarn lint
    - run: yarn ci:test
      env:
        CI: true
