version: '3'

services:
  app:
    build: .
    env_file: .env
    ports:
     - "8082:8082"
    volumes:
     - .:/usr/src/app

  # POSTFRESQL
  db:
    image: postgres:12
    command: postgres -c 'max_connections=200'
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cosplay
    ports:
    - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
